config:
  bind: 0.0.0.0:25565
  onlineMode: true
  forwarding:
    mode: none
  lite:
        enabled: false
        routes:
            - backend: '127.0.0.1:25602'
              backend-transfer: 127.0.0.1:25603
              fallback:
                motd: |
                    §7Unknown server error.
                version:
                    name: §cconnecting...
                    protocol: -1
              host: '127.0.0.1.sslip.io'
              proxyProtocol: true
              region: Moldova
              cachePingTTL: -1s
  forceKeyAuthentication: false

autotransfer:
  enabled: true
  transfer: false
  delay: 0s

geosteer:
  enabled: true
  dbPath: GeoLite2-Country.mmdb
  strict: false
